---
to: ../../<%= name %>/.github/workflows/main.yml
---

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    uses: stampedeapp/actions/.github/workflows/deploy-production.yml@main
    secrets: inherit
    with:
      stack-name: <%= stack %>
