name: Execute predeploy steps
description: Execute predeploy steps

inputs:
  github-token:
    description: |
      Token with which to check the code freeze status.
      If not provided, will skip the code freeze check
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: stampedeapp/actions/check-code-freeze@main
      if: ${{ inputs.github-token != '' }}
      with:
        github-token: ${{ inputs.github-token }}
    - uses: stampedeapp/actions/setup@main
    - id: predeploy
      name: Check for predeploy script
      shell: bash
      run: echo "script=$(cat package.json | jq -r .scripts.predeploy)" >> $GITHUB_OUTPUT
    - shell: bash
      if: ${{ steps.predeploy.outputs.script != 'null' }}
      name: Run predeploy script
      run: yarn predeploy
