name: Run Cypress
description: Clones the repository, installs dependencies, and runs Cypress.

inputs:
  e2e-testing-key:
    description: The SSH key to use for the E2E testing repository.
    default: ''
    required: true
  wait-on:
    description: The URL to wait on before running Cypress.
    default: ''
    required: false
  start:
    description: Start
    default: ''
    required: false

runs:
    using: composite
    steps:
      - name: Checkout E2E testing
        uses: actions/checkout@v3.1.0
        with:
          repository: 'stampedeapp/e2e-testing'
          ref: main
          path: e2e-testing
          ssh-key: ${{ inputs.e2e-testing-key }}

      # We remove the git info from cypress so that it picks up 
      # the correct git info from the parent repository - `web`
      - name: Remove Cypress Git Info
        shell: bash
        working-directory: e2e-testing
        run: rm -rf .git

      - name: Log CI Run ID
        shell: bash
        run: echo '${{ github.repository }}-${{ github.workflow }}-${{ github.sha }}-${{ github.run_attempt }}'

      - name: Cypress run
        uses: cypress-io/github-action@v4

        with:
          working-directory: e2e-testing 
          start: ${{ inputs.start }}
          wait-on: ${{ inputs.wait-on }}
          record: true
          parallel: true
          browser: chrome
          headed: true
          ci-build-id: '${{ github.repository }}-${{ github.workflow }}-${{ github.sha }}-${{ github.run_attempt }}'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e-testing/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: e2e-testing/cypress/videos
