name: Sourcegraph
description: Send sourcegraph info

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v3.5

  - name: Generate LSIF data
    shell: bash
    run: npx @sourcegraph/lsif-tsc -p .

  - name: Upload LSIF data
    uses: docker://sourcegraph/src-cli:latest
    env:
      SRC_ENDPOINT: https://letsdothis.sourcegraph.com
      SRC_ACCESS_TOKEN: ${{ env.SOURCEGRAPH_ACCESS_TOKEN }}
    with:
      args: lsif upload -repo=github.com/${{ github.repository }}
