name: Install Dependencies
description: |
  Install dependencies for the project.

inputs:
  npm-token:
    description: "NPM token"
    default: ""
    required: false
  production:
    description: Whether to install production dependencies
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ inputs.production }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-${{ inputs.production }}-
    - name: Use Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
    - name: "Install Dependencies"
      run: yarn --frozen-lockfile --quiet --production=${{ inputs.production }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
