---
to: ../../<%=name%>/.github/workflows/stats.yml
---
name: Stats (<%= name %>)

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  ci:
    uses: stampedeapp/actions/.github/workflows/stats.yml@main
    secrets: inherit
