name: Run Cypress
description: Clones the repository, installs dependencies, and runs Cypress.

inputs:
  github-token:
    description: The GitHub token to use for accesing the Github API
    default: ''
    required: true

runs:
    using: composite

    steps:
      - name: Check if file exists
        id: check-file
        shell: bash
        run: |
          export RESPONSE=$(
            curl -H "Authorization: Bearer ${{ inputs.github-token }}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/stampedeapp/freeze/contents/freeze
          )
          printf '%s' "$RESPONSE" | grep "Not Found" || echo "reason=$(printf '%s' "$RESPONSE" | jq -r '.content' | base64 -d)" >> $GITHUB_OUTPUT
      - name: Fail if file exists
        if: steps.check-file.outputs.reason != ''
        shell: bash
        run: |
          echo "Workflow failed due to code freeze in effect (${{ steps.check-file.outputs.reason }})" >> $GITHUB_STEP_SUMMARY
          echo "Code freeze is in effect with reason ${{ steps.check-file.outputs.reason }}."
          exit 1
