name: Run Jest
description: Runs jest tests

inputs:
  shard-number:
    description: Shard number
    default: "1"
  shard-total:
    description: Total number of shards
    default: "1"
  workers:
    description: number of jest workers to run with
    default: "2"

runs:
  using: composite
  steps:
    - name: Run Jest
      shell: bash
      run: yarn jest --maxWorkers=${{ inputs.workers }} --shard=${{ inputs.shard-number }}/${{ inputs.shard-total }} --ci --coverage --testLocationInResults --forceExit
      env:
        NODE_ENV: test
