---
to: ../../<%= name %>/.github/workflows/emergency_deploy.yml
---

name: Emergency Deployment (<%= name %>)

on:
  workflow_dispatch:
    inputs:
      reuse-image:
        description: 'Try to reuse previously built image?'
        required: false
        default: false
        type: boolean
      sha:
        description: 'SHA to deploy'
        required: false
        default: ''
        type: string

jobs:
  ci:
    uses: stampedeapp/actions/.github/workflows/emergency-deploy.yml@main
    secrets: inherit
    with:
      stack-name: <%= stack %>
      reuse-image: ${{ github.event.inputs.reuse-image == 'true' }}
      sha: ${{ github.event.inputs.sha }}
