---
to: ../../<%= name %>/.github/workflows/emergency_deploy.yml
---

name: Emergency Deployment (<%= name %>)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA to deploy'
        required: false
        default: ''
        type: string

jobs:
  ci:
    uses: stampedeapp/actions/.github/workflows/emergency-deploy.yml@main
    secrets: inherit
    with:
      stack-name: <%= stack %>
      sha: ${{ github.event.inputs.sha }}
