name: Execute terraform plan
description: Execute terraform plan

inputs:
  flags:
    description: The flags to pass to terraform plan
    required: false
    default: ""
  cli_config_credentials_token:
    description: The CLI config credentials token to use for deployment.
    required: true
  dry-run:
    description: If true, just runs terraform plan
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ inputs.cli_config_credentials_token }}

    - name: Config Terraform plugin cache
      shell: bash
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache

    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      shell: bash
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan -no-color ${{ inputs.flags }}

    - name: Terraform Apply
      if: ${{ inputs.dry-run == 'false' }}
      id: apply
      shell: bash
      run: terraform apply -no-color ${{ inputs.flags }} -auto-approve
