---
to: ../../<%=name%>/.github/workflows/pr.yml
---
name: PR

on: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@lts
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - run: yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - run: yarn lint
  jest:
    name: Jest Test
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - uses: stampedeapp/actions/jest@lts
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
      - uses: stampedeapp/actions/jest-coverage@lts
        with:
          code-climate-key: ${{ secrets.CODE_CLIMATE_KEY }}
