---
to: ../../<%=name%>/.github/workflows/pr.yml
---
name: PR (<%= name %>)

on: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@main
  static:
    needs: install-dependencies
    uses: stampedeapp/actions/.github/workflows/static.yml@main
    secrets: inherit
