---
to: ../../<%= name %>/.github/workflows/dev.yml
---

name: Dev (<%= name %>)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  ci:
    uses: stampedeapp/actions/.github/workflows/deploy.yml@monorepo
    secrets: inherit
    with:
      stack-name: <%= stack %>
