---
to: ../../<%= name %>/.github/workflows/dev.yml
---

name: Deploy (dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@lts
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - run: yarn tsc --noEmit
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - run: yarn lint
  jest:
    name: Jest Test
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: stampedeapp/actions/setup@lts
      - uses: stampedeapp/actions/jest@lts
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
      - uses: stampedeapp/actions/jest-coverage@lts
        with:
          code-climate-key: ${{ secrets.CODE_CLIMATE_KEY }}
  deploy-to-ecr:
    name: Build and Deploy to ECR
    environment: Development
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@lts
      - uses: stampedeapp/actions/deploy-to-ecr@lts
        with:
          ldt-environment: dev
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
  create-changeset:
    name: Create changeset
    runs-on: ubuntu-latest
    environment: Development
    concurrency:
      group: cloudformation-dev
    needs:
      - deploy-to-ecr
      - typecheck
      - lint
      - jest
    steps:
      - uses: actions/checkout@v3
      - uses: stampedeapp/actions/deploy-to-cloudformation@lts
        with:
          stack-name: <%= stack %>
          no-execute-changeset: false
          ldt-environment: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cloudformation-role-arn: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
