name: Next.JS Build
description: Builds the Next.JS application

inputs:
  directory:
    description: "Which directory to cache"
    default: .next/cache
    required: false

runs:
  using: composite
  steps:
    - name: Cache Next.JS build cache
      uses: actions/cache@v3
      with:
        key: |
          ${{ runner.os }}-${{ inputs.directory }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
        path: |
          ~/.npm
          ${{ github.workspace }}/${{ inputs.directory }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.directory }}-nextjs-

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v1

    - name: Build
      run: doppler run -- yarn build
      shell: bash
      env:
        # Increase max heap size to make the build run as efficiently as possible
        NODE_OPTIONS: "--max_old_space_size=4096"
        DISABLE_ESLINT_TSC_CI: "true"
