name: Run Jest Coverage Upload
description: Sends jest coverage to Codeclimate

inputs:
  code-climate-key:
    description: Key to use to upload to Code Climate. Uses env.CC_TEST_REPORTER_ID if not set
    default: ''

runs:
  using: composite

  steps:
    - uses: stampedeapp/codeclimate-action@monorepo
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage/*.lcov:lcov
      env:
        CC_TEST_REPORTER_ID: ${{ inputs.code-climate-key == '' && env.CC_TEST_REPORTER_ID || inputs.code-climate-key }}
