name: Run Jest Coverage Upload
description: Sends jest coverage to Codeclimate

inputs:
  code-climate-key:
    description: Key to use to upload to Code Climate. Uses env.CC_TEST_REPORTER_ID if not set
    default: ''

runs:
  using: composite

  steps:
    - uses: actions/download-artifact@v3
      with:
        name: coverage-artifacts
        path: coverage
    - uses: stampedeapp/codeclimate-action@main
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage/*.lcov:lcov
      env:
        CC_TEST_REPORTER_ID: ${{ inputs.code-climate-key == '' && env.CC_TEST_REPORTER_ID || inputs.code-climate-key }}
    - uses: actions/upload-artifact@v3.1.1
      if: always()
      with:
        name: coverage
        path: coverage
