name: Setup
description: Setup node and restore dependencies from cache

inputs:
  production:
    description: Whether to use production dependencies
    default: "false"
    required: false
  ref:
    description: The branch, tag or SHA to checkout.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3.5.0
      with:
        ref: ${{ inputs.ref }}
    - uses: martijnhols/actions-cache/restore@v3.0.11b
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ inputs.production }}-${{ hashFiles('**/yarn.lock') }}
    - name: Ensure cache hit
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' && env.NODE_AUTH_TOKEN == '' }}
      run: |
        echo "Could not find cache result for the current workflow."
        echo "This means that something went wrong with the 'install-dependencies' step before this job was run."
        echo "Please re-run the workflow. If the problem continues send the workflow to the platform team."
        exit 1
    - name: Use Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
    - name: Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: yarn --frozen-lockfile --quiet --production=${{ inputs.production }}
      shell: bash
