name: Setup
description: Setup node and restore dependencies from cache

inputs:
  production:
    description: Whether to use production dependencies
    default: "false"
    required: false
  ref:
    description: The branch, tag or SHA to checkout.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3.1.0
      with:
        ref: ${{ inputs.ref }}
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - uses: martijnhols/actions-cache/restore@v3
      id: cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ inputs.production }}-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
    - name: Install Dependencies
      run: yarn --frozen-lockfile --quiet --production=${{ inputs.production }} --prefer-offline
      shell: bash
