name: Check production deployed successfully
description: Ensured that the production deployment was successful.

inputs:
  github_token:
    description: The CLI config credentials token to use for deployment.
    required: true

runs:
  using: composite
  steps:
    - name: Get deployment status
      id: check-file
      shell: bash
      run: |
        export RESPONSE=$(
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/deployments?environment=Production\&per_page=1
        )
        export STATUSES_URL=$(printf '%s' "$RESPONSE" | jq -r '.[0].statuses_url')
        export RESPONSE=$(
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
              $STATUSES_URL?per_page=1
        );
        echo "response=$( printf '%s' "$RESPONSE" | jq -r '.[0].state' )" >> $GITHUB_OUTPUT
    - name: Fail if response was error
      shell: bash
      if: steps.check-file.outputs.response == 'error'
      run: |
        echo "Don't merge to main if the production deployment is not successful!"
        exit 1
