name: AWS - ECS Deploy

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        required: true
        description: Name of the stack to update
      region:
        type: string
        default: "eu-west-1"
      environment:
        type: string
        required: true
        description: GitHub environment that we want to deploy
      ldt-env:
        type: string
        required: true
        description: LDT_ENV variable value for predeploy
      ldt-environment:
        type: string
        required: true
        description: Name of the LDT config we're pushing
      run-e2e-tests:
        type: string
        required: false
        description: Should we run e2e tests?
        default: false
      check-code-freeze:
        type: string
        required: false
        description: Should we check code freeze?
        default: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  codefreeze:
    runs-on: ubuntu-latest
    name: "Run Code Freeze check"
    steps:
      - uses: stampedeapp/actions/check-code-freeze@main
        if: ${{ inputs.check-code-freeze == 'true' }}
        with:
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
      - run: echo 'Done'

  cloudformation:
    runs-on: ubuntu-latest
    name: "Cloudformation Validate"
    steps:
      - uses: stampedeapp/actions/setup@main
      - name: Validate Cloudformation Files
        uses: stampedeapp/actions/cloudformation-validate@main
        with:
          environment: ${{ inputs.ldt-environment }}

  docker:
    runs-on: ubuntu-latest-16-cores
    environment: ${{ inputs.environment }}
    name: "Build Dockerfile"
    steps:
      - uses: stampedeapp/actions/setup@main
      - name: Configure AWS credentials
        shell: bash
        run: |
          echo "AWS_DEFAULT_REGION=${{ inputs.region }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ inputs.region }}" >> $GITHUB_ENV

      - name: Assume cloudformation role
        shell: bash
        run: |
          aws sts assume-role \
            --role-arn ${{ secrets.CLOUDFORMATION_ROLE_ARN }} \
            --role-session-name github-actions-cloudformation \
            --query 'Credentials' \
            --output json > /tmp/credentials
          echo "AWS_ACCESS_KEY_ID=$(jq -r .AccessKeyId /tmp/credentials)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(jq -r .SecretAccessKey /tmp/credentials)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(jq -r .SessionToken /tmp/credentials)" >> $GITHUB_ENV
          echo "::add-mask::$AWS_SESSION_TOKEN" &>/dev/null
          echo "::add-mask::$AWS_SECRET_ACCESS_KEY" &>/dev/null
          echo "::add-mask::$AWS_ACCESS_KEY_ID" &>/dev/null

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ inputs.ldt-environment }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx-${{ inputs.ldt-environment }}

      - name: Check file existence
        id: is_nextjs
        uses: andstor/file-existence-action@v2
        with:
          files: "next.config.js"

      - name: Next.JS Build
        if: steps.is_nextjs.outputs.files_exists == 'true'
        uses: stampedeapp/actions/nextjs-build@main
        env:
          LDT_SENTRY_DRYRUN: "false"
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DEPLOY_TOKEN }}
          DISABLE_ESLINT_TSC_CI: "true"

      - name: Push resources to S3
        if: steps.is_nextjs.outputs.files_exists == 'true'
        shell: bash
        run: aws s3 sync .next/static ${{ secrets.S3_PATH }}/_next/static --acl public-read --exclude "*.map"

      - name: Build, tag, and push docker image to Amazon ECR Public
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_READONLY_TOKEN }}
            COMMIT_HASH=${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Move cache
        shell: bash
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy-and-test:
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.stack-name }}-${{inputs.environment}}
    name: "AWS Deploy"
    uses: "stampedeapp/actions/.github/workflows/aws-ecs-deploy-and-test.yml@main"
    needs:
      - docker
      - cloudformation
      - codefreeze
    secrets: "inherit"
    with:
      stack-name: ${{ inputs.stack-name }}
      region: ${{ inputs.region }}
      environment: ${{ inputs.environment }}
      ldt-env: ${{ inputs.ldt-env }}
      ldt-environment: ${{ inputs.ldt-environment }}
      run-e2e-tests: ${{ inputs.run-e2e-tests }}
