name: Deploy

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      sha:
        type: string
        description: SHA of the commit to use for deployment
        required: false
        default: ${{ github.sha }}
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ''
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@main

  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@main
    needs: install
    secrets: inherit
    with:
      test-setup-command: ${{ inputs.test-setup-command }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: stampedeapp/actions/setup@main
      - uses: stampedeapp/actions/deploy-to-ecr@wip
        env:
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
        with:
          ldt-environment: dev
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
          github-sha: ${{ inputs.sha }}
  
  execute-changeset:
    runs-on: ubuntu-latest-4-cores
    environment: Development
    needs:
      - static
      - build
    concurrency:
      group: cloudformation-dev
    steps:
      - uses: stampedeapp/actions/predeploy@main
        env:
          LDT_ENV: dev
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      - uses: stampedeapp/actions/deploy-to-cloudformation-cli@main
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: dev
          github-sha: ${{ inputs.sha }}

