name: Deploy (staging)

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      run-e2e-tests:
        type: string
        description: Run e2e tests before deploying
        required: false
        default: 'false'
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ''


env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@main

  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@main
    needs: install
    secrets: inherit
    with:
      test-setup-command: ${{ inputs.test-setup-command }}

  build-staging:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: stampedeapp/actions/setup@main
      - uses: stampedeapp/actions/deploy-to-ecr@main
        with:
          ldt-environment: staging
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy-staging:
    runs-on: ubuntu-latest
    environment: Staging
    needs:
      - static
      - build-staging
    concurrency:
      group: cloudformation-staging
    steps:
      - uses: stampedeapp/actions/check-code-freeze@main
        with:
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
      - uses: stampedeapp/actions/deploy-to-cloudformation-cli@main
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: staging
      
      - uses: stampedeapp/actions/.github/workflows/cypress.yml@main
        if: ${{ inputs.run-e2e-tests == 'true' }}
