name: Deploy

on:
  workflow_call:
    inputs:
      ldt-environment:
        type: string
        description: LDT environment to use
        required: true
      environment:
        type: string
        required: true
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      run-static-checks:
        type: string
        description: Run static checks before deploying
        required: false
        default: 'true'
      reuse-image:
        type: string
        description: 'Reuse existing image if it exists?'
        required: false
        default: 'false'
      sha:
        type: string
        description: SHA of the commit to use for deployment
        required: false
        default: ${{ github.sha }}

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  install:
    if: ${{ inputs.run-static-checks != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@wip

  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@wip
    if: ${{ inputs.run-static-checks != 'false' }}
    needs: install
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: install
    if: ${{ always() && (inputs.run-static-checks == 'false' || needs.install.result == 'success') }}
    steps:
      - uses: stampedeapp/actions/setup@wip
      - uses: stampedeapp/actions/deploy-to-ecr@wip
        with:
          ldt-environment: ${{ inputs.ldt-environment }}
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
          reuse-image: ${{ inputs.reuse-image }}
          github-sha: ${{ inputs.sha }}
  
  execute-changeset:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - static
      - build
    if: ${{ always() && (inputs.run-static-checks == 'false' || needs.static.result == 'success') && needs.build.result == 'success' }}
    concurrency:
      group: cloudformation-${{ inputs.ldt-environment }}
    steps:
      - uses: stampedeapp/actions/check-code-freeze@wip
        with:
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
      - uses: stampedeapp/actions/deploy-to-cloudformation-cli@wip
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: ${{ inputs.ldt-environment }}
          github-sha: ${{ inputs.sha }}

