name: Deploy

on:
  workflow_call:
    inputs:
      ldt-environment:
        type: string
        description: LDT environment to use
        required: true
      environment:
        type: string
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true

jobs:
  deploy:
    name: Deploy (${{ inputs.ldt-environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: cloudformation-${{ inputs.ldt-environment }}
    steps:
      - uses: stampedeapp/actions/check-code-freeze@main
        with:
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
      - uses: stampedeapp/actions/deploy-to-cloudformation@main
        with:
          stack-name: GraphQL
          no-execute-changeset: false
          ldt-environment: ${{ inputs.ldt-environment }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cloudformation-role-arn: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
