name: Deploy

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ''
      working-directory:
        type: string
        description: Directory to run the pipeline in
        required: false
        default: '.'

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
  WORKING_DIRECTORY: ${{ inputs.working-directory }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@monorepo
        with:
          working-directory: ${{ inputs.working-directory }}

  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@monorepo
    needs: install
    secrets: inherit
    with:
      test-setup-command: ${{ inputs.test-setup-command }}
      working-directory: ${{ inputs.working-directory }}
  
  execute-changeset:
    runs-on: ubuntu-latest-16-cores
    environment: Development
    needs:
      - static
    concurrency:
      group: ${{ inputs.stack-name }}-Development
    steps:
      - uses: stampedeapp/actions/predeploy@monorepo
        env:
          LDT_ENV: dev
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      - uses: stampedeapp/actions/deploy@monorepo
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: dev
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DEPLOY_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          s3-path: ${{ secrets.S3_PATH }}
          working-directory: ${{ inputs.working-directory }}

