name: Static

on:
  workflow_call:
    inputs:
      wait-on:
        type: string
        description: Wait on a job to complete before executing changeset
        required: false
        default: ''

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}

jobs:
  deploy-to-ecr:
    name: Build and Deploy to ECR
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@lts
      - uses: stampedeapp/actions/deploy-to-ecr@lts
        with:
          ldt-environment: dev
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
  create-changeset:
    name: Create changeset
    runs-on: ubuntu-latest
    environment: Development
    concurrency:
      group: cloudformation-dev
    needs:
      - deploy-to-ecr
      - typecheck
      - lint
      - jest
    steps:
      - uses: stampedeapp/actions/deploy-to-cloudformation@lts
        with:
          stack-name: GraphQL
          no-execute-changeset: false
          ldt-environment: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cloudformation-role-arn: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
