name: Build

on:
  workflow_call:

jobs:
  e2e-testing:
    name: E2E Testing
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106
    needs: create-changeset-staging
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: stampedeapp/actions/setup@lts
      - uses: stampedeapp/actions/run-cypress@lts
        with: 
          e2e-testing-key: ${{ secrets.E2E_TESTING_KEY }}
        env:
          ENV: staging
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_DEPLOYSENTINEL_KEY: ${{ secrets.CYPRESS_DEPLOYSENTINEL_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
