name: Deploy (production)

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true


env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@main

  deploy-production:
    runs-on: ubuntu-latest-16-cores
    environment: Production
    needs: install
    concurrency:
      group: cloudformation-production
    steps:
      - uses: stampedeapp/actions/predeploy@main
        with: 
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
        env:
          LDT_ENV: production
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          
      - uses: stampedeapp/actions/deploy@main
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: prod
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DEPLOY_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          s3-path: ${{ secrets.S3_PATH }}
