name: Deploy (staging)

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ""

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/install-dependencies@main

  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@main
    needs: install
    secrets: inherit
    with:
      test-setup-command: ${{ inputs.test-setup-command }}

  deploy-staging:
    needs: install
    uses: stampedeapp/actions/.github/workflows/aws-ecs-deploy.yml@main
    with:
      ldt-env: "staging"
      ldt-environment: "staging"
      stack-name: ${{ inputs.stack-name }}
      environment: "Staging"
      run-e2e-tests: true
    secrets: inherit
