name: Deploy (staging)

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        description: Name of the stack to deploy to
        required: true
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ''


env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  static:
    uses: stampedeapp/actions/.github/workflows/static.yml@main
    secrets: inherit
    with:
      test-setup-command: ${{ inputs.test-setup-command }}
  
  deploy-staging:
    runs-on: ubuntu-latest-4-cores
    environment: Staging
    needs:
      - static
    concurrency:
      group: cloudformation-staging
    steps:
      - uses: stampedeapp/actions/predeploy@main
        with: 
          github-token: ${{ secrets.WORKFLOW_CALL_TOKEN }}
        env:
          LDT_ENV: staging
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      - uses: stampedeapp/actions/deploy@main
        with:
          stack-name: ${{ inputs.stack-name }}
          ldt-environment: staging
          npm-token: ${{ secrets.NPM_READONLY_TOKEN }}
          docker-hub-username: ${{ secrets.DOCKER_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_DEPLOY_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          s3-path: ${{ secrets.S3_PATH }}

  e2e-testing:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106
    needs: deploy-staging
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - uses: stampedeapp/actions/setup@main
      - uses: stampedeapp/actions/run-cypress@main
        timeout-minutes: 30
        with: 
          e2e-testing-key: ${{ secrets.E2E_TESTING_KEY }}
        env:
          ENV: staging
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_DEPLOYSENTINEL_KEY: ${{ secrets.CYPRESS_DEPLOYSENTINEL_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
