name: Static

on:
  workflow_call:
    inputs:
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ''

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: yarn tsc
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: yarn lint
  jest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: ldtadmin
          POSTGRES_DB: segmentationservice
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: ${{ inputs.test-setup-command }}
        if: ${{ inputs.test-setup-command != '' }}
      - uses: stampedeapp/actions/jest@main
      - uses: stampedeapp/actions/jest-coverage@main
