name: Static

on:
  workflow_call:
    inputs:
      test-setup-command:
        type: string
        description: Command to run to setup the test environment
        required: false
        default: ""

env:
  DEEPSOURCE_DSN: "${{ secrets.DEEPSOURCE_DSN }}"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: yarn tsc
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: yarn lint

  cloudformation:
    name: Cloudformation Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: "Check file existence"
        uses: andstor/file-existence-action@v2
        id: check_files
        with:
          files: "cloudformation/cloudformation.yaml"

      - name: CFN Lint
        uses: scottbrenner/cfn-lint-action@v2
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          command: cfn-lint -r eu-west-1 -t ./cloudformation/cloudformation.yaml

  cloudformation-parameters-validation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ["dev", "staging", "prod"]
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: stampedeapp/actions/cloudformation-validate@main
        with:
          environment: ${{ matrix.environment }}
  jest:
    runs-on: ubuntu-latest-4-cores
    timeout-minutes: 30
    steps:
      - uses: stampedeapp/actions/setup@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: ${{ inputs.test-setup-command }}
        if: ${{ inputs.test-setup-command != '' }}

      - if: ${{ always() && env.DEEPSOURCE_DSN != '' }}
        run: curl https://deepsource.io/cli | sh

      - name: Run Jest
        shell: bash
        run: yarn jest --maxWorkers=2 --ci --coverage --coverageReporters=cobertura --testLocationInResults --forceExit

      - if: ${{ always() && env.DEEPSOURCE_DSN != '' }}
        run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
