name: Stats

on: workflow_call

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

jobs:
  type-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: yarn global add type-coverage typescript
      - name: Get type coverage
        run: |
          export coverage=$(type-coverage | head -n 1 | grep -oE "[^ ]+$")
          echo "coverage=${coverage%?}" >> $GITHUB_ENV
          echo "Coverage: $coverage" >> $GITHUB_STEP_SUMMARY
      - name: Upload to datadog
        uses: masci/datadog@v1
        with: 
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: gauge
              name: code.typescript_coverage
              value: ${{ env.coverage }}
              tags:
                - "repo:${{ github.repository }}"
                - "service:${{ github.event.repository.name }}"
                - "branch:${{ github.ref }}"

  typescript-percent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Get typescript percent
        run: |
          export percent=$(echo "$(find src -name '*.ts' | wc -l | xargs) / $(find src -name '*.[tj]s' | wc -l | xargs) * 100" | bc -l)
          echo "percent=${percent%?}" >> $GITHUB_ENV
          echo "Typescript percent: $percent%" >> $GITHUB_STEP_SUMMARY
      - name: Upload to datadog
        uses: masci/datadog@v1
        with: 
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: gauge
              name: code.typescript_percentage
              value: ${{ env.percent }}
              tags:
                - "repo:${{ github.repository }}"
                - "service:${{ github.event.repository.name }}"
                - "branch:${{ github.ref }}"
