name: Static

on:
  workflow_call:
    inputs:
      setup-step:
        description: 'Setup step that is called before all commands'
        default: ''
        type: string

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: ${{ inputs.setup-step }}
        if: ${{ inputs.setup-step != '' }}
      - run: yarn tsc
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: stampedeapp/actions/setup@main
      - run: ${{ inputs.setup-step }}
        if: ${{ inputs.setup-step != '' }}
      - run: yarn lint
  jest:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ inputs.setup-step }}
        if: ${{ inputs.setup-step != '' }}
      - uses: stampedeapp/actions/setup@main
      - uses: stampedeapp/actions/jest@main
      - uses: stampedeapp/actions/jest-coverage@main
